//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.awt.Color


class BooleanSVarViewGenerator883db8555e90401ab4e0ec28ce59982d extends SVarViewGenerator[Boolean] {

  def generate: SVarView[Boolean] = new SVarView[Boolean] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    //Todo: Implement yourself!
    val component = new Label() {
      opaque = true
    }

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    //Todo: Implement yourself!
    def update(sVarValue: Boolean) {
      component.background = if(sVarValue) Color.GREEN else Color.RED
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Red and Green View"

}