//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.lang.Boolean

class BooleanSVarSetterGeneratorbc3c1c8da9e946cb8c26b5887e725e41 extends SVarSetterGenerator[Boolean] {

  def generate: SVarSetter[Boolean] = new SVarSetter[Boolean] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Boolean): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Click me to set the svar") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          //Dialog.showMessage(null, "Use 'e' button to edit the code", "Setter not implemented yet")

          if(status) status = false else status = true
          setSvar(status)
          updateButton()

      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    override def update(newValue: Boolean): Unit = {
      status = newValue
      updateButton()
    }

    private def updateButton() {
      component.asInstanceOf[Button].text = (""+status)
    }

    var status: Boolean = false

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Boolean Setter"

}