//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._

class BooleanSVarSetterGenerator945337032d9a4019b6be3a8387fd15bd extends SVarSetterGenerator[Boolean] {

  def generate: SVarSetter[Boolean] = new SVarSetter[Boolean] {

//AutoGenerated END
//Put your code below

    private var value: Option[Boolean] = None

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Boolean): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Awaiting SVar value") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          value.collect{case v =>
            setSvar(!v)
            text = "Toggle value to " + !v
            value = Some(!v)
          }
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    override def update(newValue: Boolean) {
      value = Some(newValue)
      component.text = "Toggle value to " + !newValue
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Boolean Setter"

}