//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.awt.Color

class ColorSVarViewGeneratord160f0c23cb84d2ab0f00b88bd85773f extends SVarViewGenerator[Color] {

  def generate: SVarView[Color] = new SVarView[Color] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    //Todo: Implement yourself!
    val component = new Label

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    //Todo: Implement yourself!
    def update(sVarValue: Color) {
      component.text = "rgba("+sVarValue.getRed+","+sVarValue.getGreen+","+sVarValue.getBlue+","+sVarValue.getAlpha+")"
      component.background = sVarValue
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Color View"

}