//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.awt.Color

class ColorSVarSetterGenerator95248257d0f94d73a4d4f86f9cd4f744 extends SVarSetterGenerator[Color] {

  def generate: SVarSetter[Color] = new SVarSetter[Color] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Color): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Click me to set the svar") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          Dialog.showMessage(null, "Use 'e' button to edit the code", "Setter not implemented yet")

          /*
          setSvar(...)
          */
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    // override def update(newValue: Color): Unit = {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Color Setter"

}