//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import simx.components.mesh.ColoredMesh

class ColoredMeshSVarViewGenerator7414401937b44fac9283d4274db0855a extends SVarViewGenerator[ColoredMesh] {

  def generate: SVarView[ColoredMesh] = new SVarView[ColoredMesh] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    //Todo: Implement yourself!
    val component = new TextArea()

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    //Todo: Implement yourself!
    def update(sVarValue: ColoredMesh) {
      component.text = ""
      component.text += "IndicesCount:\t\t"+sVarValue.getIndicesCount+"\n"
      component.text += "VerticesCount:\t\t"+sVarValue.getVerticesCount+"\n"
      component.text += "NormalCount:\t\t"+sVarValue.getNormalCount+"\n"
      component.text += "TexCoordsCount:\t"+sVarValue.texCoords.length+"\n"
      component.text += "ColorsCount:\t\t"+sVarValue.colors.length+"\n"
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "ColoredMesh View"

}