//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.awt.Color
import javax.swing.JColorChooser

class ColorSVarSetterGeneratorfe7f4cec6e4246c2b922c328dd4d57d5 extends SVarSetterGenerator[Color] {

  private var currentColor = Color.white

  def generate: SVarSetter[Color] = new SVarSetter[Color] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Color): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Click me to set the color") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          setSvar(JColorChooser.showDialog(null, "Choose color", currentColor))

          /*
          setSvar(...)
          */
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    override def update(newValue: Color): Unit = {
      currentColor = newValue
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Color Setter"

}