//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import simplex3d.math.floatx.ConstVec3f
import java.awt.Color

class ConstVec3fSVarViewGeneratore35d98031cf74ec79e5a46f3577701d6 extends SVarViewGenerator[ConstVec3f] {

  def generate: SVarView[ConstVec3f] = new SVarView[ConstVec3f] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    //Todo: Implement yourself!
    val component = new Label {
      opaque = true
      background = Color.white
    }

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    //Todo: Implement yourself!
    def update(sVarValue: ConstVec3f) {
      if(sVarValue != simplex3d.math.float.Vec3.Zero) {
        component.text = (for(i <- 0 until 3) yield sVarValue(i)).map(_.formatted("%4.3f%n")).mkString("("," ,",")")
        component.background = Color.green
      }
      else {
        component.background = Color.red
      }
    }
  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Push View"

}