//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.io.File
import javax.swing.JFileChooser


class FileSVarSetterGenerator88daf25e7d584926a79f97858bd30802 extends SVarSetterGenerator[File] {

  def generate: SVarSetter[File] = new SVarSetter[File] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: File): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Open file chooser") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          val fileChooser = new JFileChooser(new File("."))
          if (fileChooser.showSaveDialog(peer) == JFileChooser.APPROVE_OPTION) {
            setSvar(fileChooser.getSelectedFile)
          }
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    // override def update(newValue: File) {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "File Chooser"

}