//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._

class FloatSVarViewGenerator020dc6c063d042fd99f7a3e978919fe3 extends SVarViewGenerator[Float] {

  def generate: SVarView[Float] = new SVarView[Float] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the value.
     */
    //Todo: Implement yourself!
    val component = new Label

    /**
      *  This function is called whenever the visualized value changes.
      *  It should update component accordingly.
      */
    //Todo: Implement yourself!
    def update(sVarValue: Float) {
      component.text = simplex3d.math.float.functions.degrees(sVarValue).toString
    }

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Angle in Degrees"

}