//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.lang.Float
import simx.core.svaractor.SVarActor

class FloatSVarSetterGeneratorac52c274df4649c4914e6bab50360036 extends SVarSetterGenerator[Float] {

  def generate: SVarSetter[Float] = new SVarSetter[Float] {

//AutoGenerated END
//Put your code below

    var speed = 2

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Float): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Press to set SVar to " + speed) {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          setSvar(speed.toFloat)
          speed = (speed+1) % 10
          this.text = "Press to set SVar to " + speed

          /*
          setSvar(...)
          */
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
     //override def update(newValue: Float): Unit = {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Silly simulationSpeed toggler"

}