//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import java.awt.Font

class FontSVarSetterGenerator47134f2e546b4c8b916aeb29f00ccddc extends SVarSetterGenerator[Font] {

  def generate: SVarSetter[Font] = new SVarSetter[Font] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Font): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Click me to set the Font") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          val fontChooser = new _root_.say.swing.JFontChooser()
          if (fontChooser.showDialog(null) == _root_.say.swing.JFontChooser.OK_OPTION)
             setSvar(fontChooser.getSelectedFont)
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    // override def update(newValue: Font) {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Font Setter"

}