//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import event.EditDone

class IntegerSVarSetterGenerator8a8c151931de45bebdbdb183ec3cb419 extends SVarSetterGenerator[Int] {

  def generate: SVarSetter[Int] = new SVarSetter[Int] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: Integer): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new TextField() {
      listenTo(this)
      reactions += {
        case event: EditDone  =>
          //Dialog.showMessage(null, "Use 'e' button to edit the code", "Setter not implemented yet")
          try {
            val value = text.toInt
            setSvar(value)
          } catch {
            case e : Throwable => println(e)
          }

          /*
          setSvar(...)
          */
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    // override def update(newValue: Integer): Unit = {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "Integer Setter"

}