//AutoGenerated Begin
//DO NOT EDIT!
package simx.components.editor.gui

import scala.swing._
import simx.core.helper.TextureData
import javax.swing.JFileChooser
import java.io.File
import javax.imageio.ImageIO


class TextureDataSVarSetterGenerator1e931f44987c4fe69be5bfeeb420689b extends SVarSetterGenerator[TextureData] {

  def generate: SVarSetter[TextureData] = new SVarSetter[TextureData] {

//AutoGenerated END
//Put your code below

    /**
     *  The scala.swing.Component that visualizes the SVar setter.
     *  Call
     *  setSvar(newValue: TextureData): Unit
     *  to set new svar value.
     */
    //Todo: Implement yourself!
    val component = new Button("Click me to set the texture") {
      listenTo(this)
      reactions += {
        case event: event.ButtonClicked =>
          val fileChooser = new JFileChooser(new File("."))
          if (fileChooser.showSaveDialog(peer) == JFileChooser.APPROVE_OPTION) {
            val img = ImageIO.read(fileChooser.getSelectedFile)
            setSvar(TextureData(img))
          }
      }
    }

    /**
     * Override update if you want to use the current value of the SVar.
     * This function is initially called once and then every time the value of the SVar changes.
     */
    // override def update(newValue: TextureData) {}

  }

  /**
   *  The name of this visualizer.
   *  This must not be unique.
   */
  //Todo: Name it!
  val name: String = "TextureData mm Setter"

}